language: android
env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3

android:
  components:
  - tools
  - tools
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}
  - extra
before_install:
- yes | sdkmanager "platforms;android-27"
script:
- "./gradlew clean build"
- cd app/build/outputs/apk/release 
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk zwave
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk app.apk"